GET https://localhost:7191/login?username=bob&password=123 HTTP/1.1
GET https://localhost:7259/login?username=bob&password=123 HTTP/1.1

GET https://localhost:7259/api/Categories/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjY1NTI1NTZCRUUzNzExRDRGRDk2QzMyQjFBRDE1QkY3IiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3MDE2NjcwNDUsImV4cCI6MTcwMTY3MDY0NSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI5NyIsImF1ZCI6ImFwaTEiLCJjbGllbnRfaWQiOiJvYXV0aENsaWVudCIsImp0aSI6IkY2OTQ5NzE0MUQ5QURCMkU1MUY5MjlFOTEzM0VCRDg3IiwiaWF0IjoxNzAxNjY3MDQ1LCJzY29wZSI6WyJhcGkxLnJlYWQiXX0.nHBsiApDSCJu8793E6vAsXT0ZHEdXceTdQyHqQItQO9uqGgF6o9ykTO7GE1VTyuqHb8PHsNhu8leI6ttpoxDKj60RTLfe9JuYVrtnbSaG1DE41heylT4jwMGoORAAMxJdp_n5AYa6ba8bvA3urrTR-5RFziE4ygsllrx5r8mcMSkN20QBMClYlEXZ0MYA4bItPzHShVqP6rw0mZzw3zh3eCSyQkJCgIbgIRhGofQL-ZVI1K8GkcyiGcCv2-oXsQvy2s7pT6IkiSOyvKaYlDlYsJukYZNTifQCPIye9p8UjnyQ8JdLfsW-C-HxVUFhJpLsxCUEgNbK8txHwi6lQz2yw


https://localhost:7191/api/Categories/